server:
  port: 8081

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:oracle:thin:@oracle:1521/XEPDB1
    username: USER_APP
    password: userpwd
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    database-platform: org.hibernate.dialect.OracleDialect
    hibernate:
      ddl-auto: update
    show-sql: true

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
  endpoints:
    web:
      exposure:
        include: health,info,metrics,circuitbreakers

jwt:
  secret: ZmxpZ2h0LWJvb2tpbmctc2VydmljZS1zZWNyZXQta2V5LWZvci1qd3QtdG9rZW4tMjU2Yml0cw==
  expiration-ms: 86400000

logging:
  file:
    name: /var/log/app/user-service.log
  level:
    com.example.userservice: DEBUG
    org.springframework.security: INFO
