server:
  port: 8084

spring:
  application:
    name: notification-service
  datasource:
    url: jdbc:oracle:thin:@oracle:1521/XEPDB1
    username: NOTIF_APP
    password: notifpwd
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    database-platform: org.hibernate.dialect.OracleDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          use_get_generated_keys: true
    show-sql: true
  sql:
    init:
      mode: always
      continue-on-error: true
  kafka:
    bootstrap-servers: kafka:9092

telegram:
  bot-token: ${TELEGRAM_BOT_TOKEN:8980252295:AAG5-RaEscsx3kLAGICCIAdVUyT51evoshQ}
  chat-id: ${TELEGRAM_CHAT_ID:1884904153}

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
  endpoints:
    web:
      exposure:
        include: health,info,metrics,circuitbreakers

logging:
  file:
    name: /var/log/app/email-service.log
  level:
    com.example.notificationservice: DEBUG
