server:
  port: 8084

spring:
  application:
    name: notification-service
  datasource:
    url: jdbc:oracle:thin:@oracle:1521/XEPDB1
    username: NOTIF_APP
    password: notifpwd
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    database-platform: org.hibernate.dialect.OracleDialect
    hibernate:
      ddl-auto: none
    show-sql: true
  sql:
    init:
      mode: always
      continue-on-error: true
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.example.notificationservice.event,com.example.orderservice.event
        spring.json.use.type.headers: false
        spring.json.type.mapping: booking.confirmed:com.example.notificationservice.event.BookingConfirmedEvent,admin.notification:com.example.notificationservice.event.AdminNotificationEvent

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
  endpoints:
    web:
      exposure:
        include: health,info,metrics,circuitbreakers

logging:
  file:
    name: /var/log/app/email-service.log
  level:
    com.example.notificationservice: DEBUG