input {
  beats {
    port => 5044
  }
}

filter {
  mutate {
    add_field => { "application" => "%{[log][file][path]}" }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "flight-booking-logs-%{+YYYY.MM.dd}"
  }
  stdout {
    codec => rubydebug
  }
}
