server:
  port: 8083

spring:
  application:
    name: order-service
  datasource:
    url: jdbc:oracle:thin:@oracle:1521/XEPDB1
    username: ORDER_APP
    password: orderpwd
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    database-platform: org.hibernate.dialect.OracleDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          use_get_generated_keys: true
    show-sql: true
  kafka:
    bootstrap-servers: kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.example.orderservice.event
        spring.json.use.type.headers: false
        spring.json.value.default.type: com.example.orderservice.event.InventoryEvent

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
  endpoints:
    web:
      exposure:
        include: health,info,metrics,circuitbreakers

resilience4j:
  circuitbreaker:
    instances:
      bookingDependency:
        sliding-window-size: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s

logging:
  file:
    name: /var/log/app/order-service.log
  level:
    io.github.resilience4j: DEBUG
