CONNECT sys/oraclepwd AS SYSDBA;

BEGIN
   EXECUTE IMMEDIATE 'CREATE USER USER_APP IDENTIFIED BY userpwd';
EXCEPTION WHEN OTHERS THEN
   IF SQLCODE != -01920 THEN
      RAISE;
   END IF;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'GRANT CONNECT, RESOURCE, CREATE SESSION, CREATE TABLE, CREATE SEQUENCE, CREATE VIEW, CREATE PROCEDURE, UNLIMITED TABLESPACE TO USER_APP';
EXCEPTION WHEN OTHERS THEN
   IF SQLCODE != -01920 THEN
      RAISE;
   END IF;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'CREATE USER PRODUCT_APP IDENTIFIED BY productpwd';
EXCEPTION WHEN OTHERS THEN
   IF SQLCODE != -01920 THEN
      RAISE;
   END IF;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'GRANT CONNECT, RESOURCE, CREATE SESSION, CREATE TABLE, CREATE SEQUENCE, CREATE VIEW, CREATE PROCEDURE, UNLIMITED TABLESPACE TO PRODUCT_APP';
EXCEPTION WHEN OTHERS THEN
   IF SQLCODE != -01920 THEN
      RAISE;
   END IF;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'CREATE USER ORDER_APP IDENTIFIED BY orderpwd';
EXCEPTION WHEN OTHERS THEN
   IF SQLCODE != -01920 THEN
      RAISE;
   END IF;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'GRANT CONNECT, RESOURCE, CREATE SESSION, CREATE TABLE, CREATE SEQUENCE, CREATE VIEW, CREATE PROCEDURE, UNLIMITED TABLESPACE TO ORDER_APP';
EXCEPTION WHEN OTHERS THEN
   IF SQLCODE != -01920 THEN
      RAISE;
   END IF;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'CREATE USER NOTIF_APP IDENTIFIED BY notifpwd';
EXCEPTION WHEN OTHERS THEN
   IF SQLCODE != -01920 THEN
      RAISE;
   END IF;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'GRANT CONNECT, RESOURCE, CREATE SESSION, CREATE TABLE, CREATE SEQUENCE, CREATE VIEW, CREATE PROCEDURE, UNLIMITED TABLESPACE TO NOTIF_APP';
EXCEPTION WHEN OTHERS THEN
   IF SQLCODE != -01920 THEN
      RAISE;
   END IF;
END;
/
COMMIT;
